name: Scan For File Changes in jtreg-buffer and Open a PR

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scan_and_pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout jdkContainerOsTests
        uses: actions/checkout@v4

      - name: Set up Git and GH CLI
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          echo ${{ secrets.TOKEN }} | gh auth login --with-token

      - name: Clone jtreg-buffer
        run: |
          gh repo clone rh-openjdk/jtreg-buffer

      - name: Check for changes in CheckAlgorithms
        run: |
          diff -u containersQa/CheckAlgorithms.java jtreg-buffer/test/reproducers/checkAlgorithms/CheckAlgorithms.java > CheckAlgorithms.patch
        continue-on-error: true

      - name: Apply patch to CheckAlgorithms
        if: ${{ steps.check_check_for_changes_in_checkalgorithms.outcome == 'failure' }}
        run: |
          patch containersQa/CheckAlgorithms.java CheckAlgorithms.patch

      - name: Check for changes in CipherList.java
        run: |
          diff -u containersQa/CipherList.java jtreg-buffer/test/reproducers/1906862/CipherList.java > CipherList.patch
        continue-on-error: true

